# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12J1q4L_25JCOsCGDdGP3QVyFfcHT8HnL
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

# 1. PARÁMETROS GLOBALES
L1, L2, L3, L4 = 0.80, 0.20, 0.90, 0.60
m2, m3, m4 = 5, 35, 10
I2, I3_base, I4 = 0.02, 2.80, 0.30
g = 9.81
RPM = 120
omega2 = RPM * (2 * np.pi / 60)
alpha2 = 0

# Coordenadas locales de la cuchilla (Constantes)
xC_loc, yC_loc = 0.45, 0.40

def simular_cizalla(xG3_loc, yG3_loc):
    """Función que simula un ciclo completo y retorna resultados clave."""
    torques_motor = []
    fuerzas_A = []

    angulos_motor = np.arange(0, 360, 1)
    aproximacion_inicial = [np.radians(10), np.radians(120)]

    def ecuaciones_posicion(incognitas, theta2):
        th3, th4 = incognitas
        eq_x = L1 - L2*np.cos(theta2) - L3*np.cos(th3) + L4*np.cos(th4)
        eq_y = -L2*np.sin(theta2) - L3*np.sin(th3) + L4*np.sin(th4)
        return [eq_x, eq_y]

    YC_prev = 0

    for angulo in angulos_motor:
        theta2 = np.radians(angulo)

        # 1. Cinemática de Posición
        th3, th4 = fsolve(ecuaciones_posicion, aproximacion_inicial, args=(theta2,))
        aproximacion_inicial = [th3, th4] # Actualizar para la sig. iteración

        # 2. Cinemática de Velocidad
        A_vel = np.array([
            [-L3*np.sin(th3),  L4*np.sin(th4)],
            [ L3*np.cos(th3), -L4*np.cos(th4)]
        ])
        B_vel = np.array([L2*omega2*np.sin(theta2), -L2*omega2*np.cos(theta2)])
        omega3, omega4 = np.linalg.solve(A_vel, B_vel)

        # 3. Cinemática de Aceleración
        B_accel = np.array([
            L2*alpha2*np.sin(theta2) + L2*omega2**2*np.cos(theta2) + L3*omega3**2*np.cos(th3) - L4*omega4**2*np.cos(th4),
            -L2*alpha2*np.cos(theta2) + L2*omega2**2*np.sin(theta2) + L3*omega3**2*np.sin(th3) - L4*omega4**2*np.sin(th4)
        ])
        alpha3, alpha4 = np.linalg.solve(A_vel, B_accel)

        # 4. Mapeo Global del Triángulo (Traslación + Rotación)
        XA, YA = L2*np.cos(theta2), L2*np.sin(theta2)
        XB, YB = L1 + L4*np.cos(th4), L4*np.sin(th4)

        XG3 = XA + xG3_loc*np.cos(th3) - yG3_loc*np.sin(th3)
        YG3 = YA + xG3_loc*np.sin(th3) + yG3_loc*np.cos(th3)

        XC = XA + xC_loc*np.cos(th3) - yC_loc*np.sin(th3)
        YC = YA + xC_loc*np.sin(th3) + yC_loc*np.cos(th3)

        # 5. Condicional Dinámico de la Cizalla
        if angulo == 0:
            YC_prev = YC

        if YC <= 0.20 and YC < YC_prev:
            Fc = 15000
        else:
            Fc = 0
        YC_prev = YC

        # 6. Aceleraciones de los Centros de Gravedad
        a2x = -L2/2 * np.cos(theta2) * omega2**2
        a2y = -L2/2 * np.sin(theta2) * omega2**2

        a3x = -L2*omega2**2*np.cos(theta2) - xG3_loc*omega3**2*np.cos(th3) - xG3_loc*alpha3*np.sin(th3) + yG3_loc*omega3**2*np.sin(th3) - yG3_loc*alpha3*np.cos(th3)
        a3y = -L2*omega2**2*np.sin(theta2) - xG3_loc*omega3**2*np.sin(th3) + xG3_loc*alpha3*np.cos(th3) - yG3_loc*omega3**2*np.cos(th3) - yG3_loc*alpha3*np.sin(th3)

        a4x = -L4/2 * np.cos(th4) * omega4**2 - L4/2 * np.sin(th4) * alpha4
        a4y = -L4/2 * np.sin(th4) * omega4**2 + L4/2 * np.cos(th4) * alpha4

        # 7. Matriz de D'Alembert (9x9)
        A_dyn = np.zeros((9, 9))
        B_dyn = np.zeros(9)

        R12x, R12y = -XA/2, -YA/2
        R32x, R32y = XA/2, YA/2
        R23x, R23y = XA - XG3, YA - YG3
        R43x, R43y = XB - XG3, YB - YG3
        RCx, RCy   = XC - XG3, YC - YG3

        # Centro de gravedad del balancín (A la mitad de L4)
        R34x, R34y = XB - (L1+XB)/2, YB - YB/2
        R14x, R14y = L1 - (L1+XB)/2, -YB/2

        # Llenado de Ecuaciones
        A_dyn[0,0]=1; A_dyn[0,2]=-1; B_dyn[0]=m2*a2x
        A_dyn[1,1]=1; A_dyn[1,3]=-1; B_dyn[1]=m2*g + m2*a2y
        A_dyn[2,0]=-R12y; A_dyn[2,1]=R12x; A_dyn[2,2]=R32y; A_dyn[2,3]=-R32x; A_dyn[2,8]=1; B_dyn[2]=I2*alpha2

        A_dyn[3,2]=1; A_dyn[3,4]=-1; B_dyn[3]=m3*a3x
        A_dyn[4,3]=1; A_dyn[4,5]=-1; B_dyn[4]=m3*g + m3*a3y + Fc
        A_dyn[5,2]=-R23y; A_dyn[5,3]=R23x; A_dyn[5,4]=R43y; A_dyn[5,5]=-R43x; B_dyn[5]=I3_base*alpha3 - (RCx*(-Fc))

        A_dyn[6,4]=1; A_dyn[6,6]=1; B_dyn[6]=m4*a4x
        A_dyn[7,5]=1; A_dyn[7,7]=1; B_dyn[7]=m4*g + m4*a4y
        A_dyn[8,4]=-R34y; A_dyn[8,5]=R34x; A_dyn[8,6]=-R14y; A_dyn[8,7]=R14x; B_dyn[8]=I4*alpha4

        X_sol = np.linalg.solve(A_dyn, B_dyn)

        torques_motor.append(X_sol[8])
        fuerzas_A.append(np.sqrt(X_sol[2]**2 + X_sol[3]**2)) # La magnitud de F23

    torque_pico = max(np.abs(torques_motor))
    fuerza_A_max = max(np.abs(fuerzas_A))

    return torque_pico, fuerza_A_max, torques_motor, fuerzas_A

# EJECUCIÓN DE MISIONES

# FASE 1: DIAGNÓSTICO DEL MODELO BASE
print(" FASE 1: DIAGNÓSTICO ")
xG3_base, yG3_base = 0.45, 0.133
t_pico_base, fA_base, torques_base, _ = simular_cizalla(xG3_base, yG3_base)
print(f"Torque Pico del diseño base: {t_pico_base:.2f} N*m")

#  FASE 2: OPTIMIZACIÓN INERCIAL
print("\n FASE 2: OPTIMIZACIÓN")
mejor_torque = float('inf')
mejor_x, mejor_y = 0, 0

# Rango: +/- 0.15m desde la posición base
x_vals = np.linspace(xG3_base - 0.15, xG3_base + 0.15, 10)
y_vals = np.linspace(yG3_base - 0.15, yG3_base + 0.15, 10)

# Bucle de búsqueda (Grid Search)
for x in x_vals:
    for y in y_vals:
        t_pico, _, _, _ = simular_cizalla(x, y)
        if t_pico < mejor_torque:
            mejor_torque = t_pico
            mejor_x = x
            mejor_y = y

print(f"Coordenadas óptimas encontradas -> x': {mejor_x:.3f} m, y': {mejor_y:.3f} m")
print(f"Nuevo Torque Pico Mínimo: {mejor_torque:.2f} N*m")

# Extraer los arreglos del diseño ganador para graficar y auditar
_, fA_optima, torques_optimos, fuerzas_A_opt = simular_cizalla(mejor_x, mejor_y)

#  FASE 3: AUDITORÍA ESTRUCTURAL
print("\n FASE 3: AUDITORÍA ESTRUCTURAL (Pasador A) ")
print(f"Fuerza Máxima en el Pasador A (F23): {fA_optima:.2f} N")

Ssy = 310 * 10**6 # Pa (Acero SAE 1045)
diametro_A = 0.018 # m (18 mm)
area_A = np.pi * (diametro_A**2) / 4
tau_A = fA_optima / area_A
FS_A = Ssy / tau_A

print(f"Esfuerzo Cortante Aplicado (Tau): {tau_A / 10**6:.2f} MPa")
print(f"Factor de Seguridad (FS): {FS_A:.2f}")

if FS_A >= 1.5:
    print("El ensamble es seguro.")
else:
    print("El ensamble falla (FS < 1.5).")

#  GRÁFICAS COMPARATIVAS
plt.figure(figsize=(12, 5))
angulos = np.arange(0, 360, 1)

# Comparación de Torques
plt.subplot(1, 2, 1)
plt.plot(angulos, torques_base, label="Diseño Base", linestyle='--', color='red')
plt.plot(angulos, torques_optimos, label="Diseño Optimizado", color='green', linewidth=2)
plt.title("Requisito de Torque: Base vs Optimizado")
plt.xlabel("Ángulo de Manivela (Grados)")
plt.ylabel("Torque (N*m)")
plt.grid(True)
plt.legend()

# Perfil de Fuerza en el Pasador A
plt.subplot(1, 2, 2)
plt.plot(angulos, fuerzas_A_opt, color='blue', linewidth=2)
plt.title("Fuerza Dinámica en el Pasador A del diseño optimizado")
plt.xlabel("Ángulo de Manivela")
plt.ylabel("Fuerza Absoluta (N)")
plt.grid(True)

plt.tight_layout()
plt.show()

